name          = "typing"
version       = "1.9.0"
license       = "MIT"
description   = "The Quirk stdlib 'typing' package."
repository    = "github.com/AlexVachon/quirk-typing"
quirk-version = ">=2.4.4"

[deps]
