name          = "typing"
version       = "1.15.1"
license       = "MIT"
description   = "The Quirk stdlib 'typing' package."
repository    = "github.com/AlexVachon/quirk-typing"
quirk-version = ">=5.1.0"

[deps]
